(define (tree->generator tree)
 (let ((yield 'undefined))
  (define (generate-leaves)
   (let loop ((fragment tree))
    (cond ((pair? fragment)
           (loop (car fragment))
           (loop (cdr fragment)))
          ((not (null? fragment))
           (call/cc (lambda (resume)
            (set! generate-leaves (lambda ()
             (resume 'dummy)))
            (yield fragment))))))
   (yield '()))
  (lambda ()
   (call/cc (lambda (k)
    (set! yield k)
    (generate-leaves))))))
